<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class M_makanan extends CI_Model
{

    public $table = 'posts';
    public $id = 'id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->where('post_cat_id ',7);
        $this->db->group_start();
        $this->db->like('id', $q);
        $this->db->or_like('post_title', $q);
        $this->db->or_like('post_cat_id', $q);
        $this->db->or_like('post_content', $q);
        $this->db->or_like('post_slug', $q);
        $this->db->or_like('post_link', $q);
        $this->db->or_like('post_img', $q);
        $this->db->or_like('created_at', $q);
        $this->db->group_end();
        $this->db->from($this->table);
        
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->from($this->table);
        $this->db->order_by($this->id, $this->order);
        $this->db->where('post_cat_id ',7);
        $this->db->group_start();
        $this->db->or_like('post_title', $q);
        $this->db->or_like('post_cat_id', $q);
        $this->db->or_like('post_content', $q);
        $this->db->or_like('post_slug', $q);
        $this->db->or_like('post_link', $q);
        $this->db->or_like('post_img', $q);
        $this->db->or_like('created_at', $q);
        $this->db->group_end();
        $this->db->limit($limit, $start);
        return $this->db->get();
    }

}

/* End of file mitra_model.php */
/* Location: ./application/models/mitra_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-11-02 11:43:18 */
/* http://harviacode.com */